dist: focal
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-10
      - clang++-10
      - gcc-10
      - g++-10
      - doxygen
      - googletest 
      - libgtest-dev 
      - graphviz
      - exuberant-ctags 
      - gcovr
      - lcov
        #after_script:
        #  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-10
script:
  - mkdir build && cd build
  - CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10 cmake ..
  - cmake --build . -- -j2
  - ctest

