dist: jammy
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - clang++
      - gcc
      - g++
      - doxygen
      - googletest
      - libgtest-dev
      - graphviz
      - exuberant-ctags
      - gcovr
      - lcov
        #after_script:
        #  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov
script:
  - mkdir build && cd build
  - CXX=/usr/bin/clang++ CC=/usr/bin/clang cmake ..
  - cmake --build . -- -j
  - ctest -j

