dist: focal
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # I couldn't get ${GCC_VER} in here successfully
      - gcc-10
      - clang-10
      - clang++-10
      - g++-10
      - doxygen
      - googletest 
      - libgtest-dev 
      - graphviz
      - exuberant-ctags 
after_script:
  - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-10
script:
  - CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10 cmake -D ENABLE_COVERAGE:BOOL=TRUE ./bitset/
  - cmake --build . -- -j2
  - ctest

