image:
  - Ubuntu2004
build_script:
- cmd: >-
    sudo apt-get clang-10 
    
    CXX=/usr/bin/clang++-10 CC=/usr/bin/clang-10 cmake ./bitset/
    
    cmake --build . -- -j2 --config "Debug"
    
    ctest  

test_script:
- cmd: ctest -C Debug
